/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MarketConfig {
  amm_lp_asset: string;
  asset_a: string;
  asset_a_q_token_raw: string;
  asset_a_q_token_ticker: string;
  asset_b: string;
  asset_b_q_token_raw: string;
  asset_b_q_token_ticker: string;
  collateral_market_id: string;
  enable: Generated<boolean>;
  leverage: number;
  market_id: string;
  min_collateral: Numeric;
}

export interface Order {
  action: string;
  collateral_amount: Numeric | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  filled_at: Timestamp | null;
  filled_price: Numeric | null;
  id: Generated<Int8>;
  leverage: Numeric | null;
  market: string;
  order_type: string;
  position_id: Int8 | null;
  price: Numeric | null;
  side: string;
  size: Numeric;
  slippage_tolerance: Numeric | null;
  status: Generated<string>;
  trigger_price: Numeric | null;
  tx_hash: string | null;
  user_address: string;
}

export interface Position {
  borrowed_amount: Numeric;
  closed_at: Timestamp | null;
  collateral_amount: Numeric;
  collateral_asset: string;
  created_at: Generated<Timestamp>;
  entry_price: Numeric;
  funding_paid: Generated<Numeric>;
  id: Generated<Int8>;
  leverage: Numeric;
  liquidation_price: Numeric;
  liqwid_borrow_id: string | null;
  liqwid_supply_id: string | null;
  market: string;
  position_size: Numeric;
  realized_pnl: Generated<Numeric>;
  side: string;
  status: Generated<string>;
  stop_loss_price: Numeric | null;
  take_profit_price: Numeric | null;
  unrealized_pnl: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  user_address: string;
}

export interface DB {
  market_config: MarketConfig;
  order: Order;
  position: Position;
}
