/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MarketConfig {
  amm_lp_asset: string;
  asset_a: string;
  asset_a_q_token_raw: string;
  asset_a_q_token_ticker: string;
  asset_b: string;
  asset_b_q_token_raw: string;
  asset_b_q_token_ticker: string;
  collateral_market_id: string;
  enable: Generated<boolean>;
  leverage: Numeric;
  market_id: string;
  min_collateral: Numeric;
}

export interface Order {
  amount_in: Numeric | null;
  amount_out: Numeric | null;
  asset_in: string | null;
  asset_out: string | null;
  built_outputs_hash: string | null;
  built_tx_id: string | null;
  built_valid_to: Timestamp | null;
  created_tx_id: string | null;
  created_tx_index: number | null;
  id: Generated<Int8>;
  order_type: string;
  position_id: Int8;
}

export interface Position {
  amount_borrow: Numeric;
  amount_in: Numeric;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  market_id: string;
  side: string;
  status: Generated<string>;
  user_address: string;
}

export interface DB {
  market_config: MarketConfig;
  order: Order;
  position: Position;
}
